version: '3.6'

services:
  ms:
    build:
      context: .
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    volumes:
      - ./src:/usr/app/src
  docs:
    image: swaggerapi/swagger-ui
    ports:
      - '${SWAGGER_PORT}:8080'
    environment:
      - SWAGGER_JSON=/app/swagger.json
    volumes:
      - ./swagger.json:/app/swagger.json
